/* WHERE É O FILTRO DO SQL, ONDE SE APLICA UMA CONDIÇÃO QUE OS DADOS PRECISAM ATENDER PARA SEREM EXIBIDOS */

-- WHERE É CASE SENSETIVE, OU SEJA TEM DIFERENCIAÇÃO DE MAIUSCULOS E minusculos
-- BETWEEN PODE SER USADO NO WHERE PARA DETERMINAR UM RANGE A SER SELECIONADO

SELECT * FROM produtos WHERE DescCategoriaProduto = 'rpg'