-- ORDER BY SERVE PARA ORDENAR OS RESULTADOS COM BASE EM UMA OU MAIS COLUNAS
-- POR PADRÃO ELE VEM COM ASC (MENOR P/ O MAIOR). PARA A ORDEM INVERSA UTILIZAMOS O DESC (MAIOR P/ MENOR)


SELECT 
    * 
FROM clientes
ORDER BY QtdePontos DESC
LIMIT 10;

-- NO CASO DE VARIOS CRITERIOS, UTILIZAMOS O ASC E O DESC DEPOIS DE APONTALOS, VIDE EXEMPLO ABAIXO
-- O ORDER BY VEM DEPOIS DO WHERE

SELECT 
    * 
FROM clientes
WHERE flTwitch = 1
ORDER BY DtCriacao ASC, QtdePontos DESC
LIMIT 10;
