-- TRAZ VALORES UNICOS DAS LINHAS PARA O RESULTADO
-- SE FOR UM DISTINCT DE APENAS UMA COLUNA, TRAZ OS VALORES UNICOS DAQUELA COLUNA
-- SE FOR UM DISTINCT COM MAIS DE UMA COLUNA, TRAZ OS VALORES UNICOS DAS COMBINACOES DAS COLUNAS INFORMADAS

SELECT DISTINCT
    flTwitch,
    flEmail
FROM clientes;

-- QUANTOS CLIENTES OPERARAM NO MÊS DE JULHO DE 2025?

SELECT 
    count(DISTINCT idCliente),
    count(IdTransacao),
    count(IdTransacao) / count(DISTINCT idCliente)
FROM transacoes
WHERE DtCriacao >= '2025-07-01' AND DtCriacao < '2025-08-01'
;
