-- SELECIONE TODOS OS CLIENTES COM EMAIL CADASTRADO

-- A COLUNA A SER FILTRADA NÃO PRECISA ESTAR NO CAMPO DE SELEÇÃO

SELECT IdCliente FROM clientes WHERE flEmail = 1

-- OUTRA ALTERNATIVA SERIA WHERE flEmail != 0